---
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - prettier

settings:
  react:
    version: "16"

plugins:
  - import
  - prettier

rules:
  no-bitwise: 0
  react-hooks/exhaustive-deps: 0
  no-return-await: 2
  import/no-unresolved: 2
  import/named: 2
  import/default: 2
  import/export: 2

env:
  browser: true
  commonjs: true
  es6: true
  node: true

parserOptions:
  ecmaFeatures:
    ecmaVersion: 6
    sourceType: module
    jsx: true
    modules: true
    experimentalObjectRestSpread: true

  sourceType: module
